#!/bin/bash

# Styles
OFF='\e[0m'               # Text Reset
BOLD="\e[1m"              # Bold
UNDERLINE="\e[4m"         # Underline

# Regular Colors
BLACK='\e[0;30m'          # Black
RED='\e[0;31m'            # Red
GREEN='\e[0;32m'          # Green
YELLOW='\e[0;33m'         # Yellow
BLUE='\e[0;34m'           # Blue
PURPLE='\e[0;35m'         # Purple
CYAN='\e[0;36m'           # Cyan
WHITE='\e[0;37m'          # White

# Bold
B_BLACK='\e[1;30m'        # Black
B_RED='\e[1;31m'          # Red
B_GREEN='\e[1;32m'        # Green
B_YELLOW='\e[1;33m'       # Yellow
B_BLUE='\e[1;34m'         # Blue
B_PURPLE='\e[1;35m'       # Purple
B_CYAN='\e[1;36m'         # Cyan
B_WHITE='\e[1;37m'        # White

# Underline
U_BLACK='\e[4;30m'        # Black
U_RED='\e[4;31m'          # Red
U_GREEN='\e[4;32m'        # Green
U_YELLOW='\e[4;33m'       # Yellow
U_BLUE='\e[4;34m'         # Blue
U_PURPLE='\e[4;35m'       # Purple
U_CYAN='\e[4;36m'         # Cyan
U_WHITE='\e[4;37m'        # White

# Background
BCK_BLACK='\e[40m'        # Black
BCK_RED='\e[41m'          # Red
BCK_GREEN='\e[42m'        # Green
BCK_YELLOW='\e[43m'       # Yellow
BCK_BLUE='\e[44m'         # Blue
BCK_PURPLE='\e[45m'       # Purple
BCK_CYAN='\e[46m'         # Cyan
BCK_WHITE='\e[47m'        # White

# High Intensity
I_BLACK='\e[0;90m'        # Black
I_RED='\e[0;91m'          # Red
I_GREEN='\e[0;92m'        # Green
I_YELLOW='\e[0;93m'       # Yellow
I_BLUE='\e[0;94m'         # Blue
I_PURPLE='\e[0;95m'       # Purple
I_CYAN='\e[0;96m'         # Cyan
I_WHITE='\e[0;97m'        # White

# Bold High Intensity
BI_BLACK='\e[1;90m'       # Black
BI_RED='\e[1;91m'         # Red
BI_GREEN='\e[1;92m'       # Green
BI_YELLOW='\e[1;93m'      # Yellow
BI_BLUE='\e[1;94m'        # Blue
BI_PURPLE='\e[1;95m'      # Purple
BI_CYAN='\e[1;96m'        # Cyan
BI_WHITE='\e[1;97m'       # White

# High Intensity backgrounds
I_BCK_BLACK='\e[0;100m'   # Black
I_BCK_RED='\e[0;101m'     # Red
I_BCK_GREEN='\e[0;102m'   # Green
I_BCK_YELLOW='\e[0;103m'  # Yellow
I_BCK_BLUE='\e[0;104m'    # Blue
I_BCK_PURPLE='\e[10;95m'  # Purple
I_BCK_CYAN='\e[0;106m'    # Cyan
I_BCK_WHITE='\e[0;107m'   # White
