#!/bin/bash

# /etc/update-motd.d/colors

# shellcheck disable=SC2034
set -euo pipefail

# Styles
OFF="\e[0m" # Text Reset
BOLD="\e[1m"
LIGHT="\e[2m"
ITALIC="\e[3m"
UNDERLINE="\e[4m"
FLASHING="\e[5m"
FAST_FLASHING="\e[6m"

# Regular colors
BLACK="\e[38;2;0;0;0m"
RED="\e[38;2;255;0;0m"
GREEN="\e[38;2;0;255;0m"
YELLOW="\e[38;2;255;255;0m"
BROWN="\e[38;2;96;64;32m"
BLUE="\e[38;2;0;0;255m"
PURPLE="\e[38;2;255;0;255m"
PINK="\e[38;2;255;96;192m"
CYAN="\e[38;2;0;255;255m"
ORANGE="\e[38;2;255;96;0m"
GREY="\e[38;2;128;128;128m"
WHITE="\e[38;2;255;255;255m"

# Backgrounds
BCK_BLACK="\e[48;2;0;0;0m"
BCK_RED="\e[48;2;255;0;0m"
BCK_GREEN="\e[48;2;0;255;0m"
BCK_YELLOW="\e[48;2;255;255;0m"
BCK_BROWN="\e[48;2;96;64;32m"
BCK_BLUE="\e[48;2;0;0;255m"
BCK_PURPLE="\e[48;2;255;0;255m"
BCK_PINK="\e[48;2;255;96;192m"
BCK_CYAN="\e[48;2;0;255;255m"
BCK_ORANGE="\e[48;2;255;96;0m"
BCK_GREY="\e[48;2;128;128;128m"
BCK_WHITE="\e[48;2;255;255;255m"

# For terminals who doesn't support 24-bit or true color
OLD_BLACK='\e[0;30m'
OLD_RED='\e[0;31m'
OLD_GREEN='\e[0;32m'
OLD_BROWN='\e[0;33m' # Can be yellow or brown depending on terminals
OLD_BLUE='\e[0;34m'
OLD_PURPLE='\e[0;35m'
OLD_CYAN='\e[0;36m'
OLD_WHITE='\e[0;37m'

# Old backrounds
OLD_BCK_BLACK="\e[40m"
OLD_BCK_RED="\e[41m"
OLD_BCK_GREEN="\e[42m"
OLD_BCK_YELLOW="\e[43m"
OLD_BCK_BLUE="\e[44m"
OLD_BCK_PURPLE="\e[45m"
OLD_BCK_CYAN="\e[46m"
OLD_BCK_WHITE="\e[47m"
