#!/bin/bash

# /etc/update-motd.d/15-debian-logo

set -euo pipefail

#https://lists.debian.org/debian-devel/2001/07/msg00686.html
echo -e "\e[0;31m
   gv_mt\$\$g.
 ,g\$\"   \"\"Y\$\",\e[0m        _     _    _           \e[0;31m
'\$P  ,,g.. \`\$:   \e[0m  __| |___| |__(_)__ _ _ _     \e[0;31m
\$\$   d' -,,\$\$   \e[0m  / _' / -_) '_ \ / _' | ' \   \e[0;31m
\$\$. \`Yb_\$_dP    \e[0m  \__,_\___|_.__/_\__,_|_||_|  \e[0;31m
\`\$bb \"-_          
 \`Y\$\b
   \`Y\$..
      \`\"\"
\e[0m"