#!/bin/bash

# /etc/update-motd.d/15-raspberry-logo

set -euo pipefail

#https://github.com/dylanaraps/neofetch/blob/master/neofetch#L9936
echo -e "\e[0;32m
   .~~.   .~~.
  '. \ ' ' / .'                                                             \e[0;31m  
   .~ .~~~..~.   \e[0m                    _                             _   \e[0;31m
  : .~.'~'.~. :  \e[0m   _ _ __ _ ____ __| |__  ___ _ _ _ _ _  _   _ __(_)  \e[0;31m
 ~ (   ) (   ) ~ \e[0m  | '_/ _' (_-< '_ \ '_ \/ -_) '_| '_| || | | '_ \ |  \e[0;31m
( : '~'.~.'~' : )\e[0m  |_| \__,_/__/ .__/_.__/\___|_| |_|  \_, | | .__/_|  \e[0;31m
 ~ .~ (   ) ~. ~ \e[0m              |_|                     |__/  |_|       \e[0;31m
  (  : '~' :  )
   '~ .~~~. ~'
       '~'
\e[0m"