#!/bin/bash

# /etc/update-motd.d/15-raspberry-logo

#set -euo pipefail

#https://asciiart.website/index.php?art=logos%20and%20insignias/linux
echo -e "\e[38;2;255;96;0m
             .-.
       .-'''(   )
    ,'\ \    '-'.
   /   \ '''-.   ' \e[0m        _             _          \e[38;2;255;96;0m
 .-.  ,       '___:\e[0m   _  _| |__ _  _ _ _| |_ _  _   \e[38;2;255;96;0m  
(   ) :        ___ \e[0m  | || | '_ \ || | ' \  _| || |  \e[38;2;255;96;0m
 '-'  '       ,   :\e[0m   \_,_|_.__/\_,_|_||_\__|\_,_|  \e[38;2;255;96;0m
   \   / ,..-'   ,
    './ /    .-.'
       '-..-(   )
             '-'
\e[0m"
